---
title: Keeping Credentials Secret with Keyrings in R
author: ''
date: '2019-01-19'
slug: keeping-credentials-secret-with-keyrings-in-r
categories: []
tags: []
---

[edit](https://github.com/ras44/blog/edit/master/content/post/2019-01-19-keeping-credentials-secret-with-keyrings-in-r.Rmd)


## Keeping credentials secret
API keys and database passwords are two examples of common credentials that users usually want to keep secret.  The following is an example of how to use the R keyrings package to store encrypted credentials locally[^1].  To do this, we only have to install and load the keyring package[^2] and define three strings: the keyring name, a keyring service, and the username that we want to associate our secret credentials with.  A simple script is provided below, also available in this [gist](https://gist.github.com/ras44/cedbe5ba0230787a3a57a8db955494d3):

```
library(keyring)

# Set variables to be used in keyring.
kr_name <- "my_keyring"
kr_service <- "my_database"
kr_username <- "my_username"

# Create a keyring and add an entry using the variables above
kb <- keyring::backend_file$new()
# Prompt for the keyring password, used to unlock keyring
kb$keyring_create(kr_name)
# Prompt for the password to be stored in the keyring
kb$set(kr_service, username=kr_username, keyring=kr_name)
# Lock the keyring
kb$keyring_lock(kr_name)

# The encrypted keyring file is now stored at ~/.config/r-keyring/ and can be
# accessed by any R program that provides the keyring password

```

This process will prompt for a password that locks and unlocks the keyring.  We only have to run through this process once, and then we can retrieve the credentials from any R project using a retrieval script.

## Retrieving credentials
To retrieve credentials, we set the same three variables and use the keyring `get()` function, which will prompt us for the keyring password that we set in the first step.  A retrieval script follows:

```
library(keyring)
library(DBI)

# Set variables to be used in keyring.
kr_name <- "my_keyring"
kr_service <- "my_database"
kr_username <- "my_username"

# Output the stored password
keyring::backend_file$new()$get(service = kr_service,
                                user = kr_username,
                                keyring = kr_name)


# Establish connection to Teradata retrieving the password from the keyring.
dbConnect(drv = odbc::odbc(),
                dsn = "my_dsn", # set DSN options in ~/.odbc.ini
                pwd = keyring::backend_file$new()$get(service = kr_service,
                                                      user = kr_username,
                                                      keyring = kr_name))

```

## Next steps
What is the benefit of using keyrings to manage credentials?  Primarily, they help to ensure that your secrets are not visible in your code.  Additionally, they help to ensure that the secrets are not saved locally.

The astute reader might note that we are hard-coding the keyring username in our scripts.  It would be better to separate configuration from logic by sourcing or parsing a user-specific configuration file that defines the three keyring variables.  If this configuration file is excluded from the repo, no user-identifiable information will be contained in the repo.



[^1]: In this case credentials are stored `~/.config/r-keyring`
[^2]: Note that the r-keyring package is automatically installed and available in [rstudio-project](https://github.com/ras44/rstudio-project). 
