---
title: Why I use a fixed version of R
author: Roland Stevenson
date: '2019-01-05'
slug: why-i-use-a-fixed-version-of-r
categories: []
tags: []
---

[edit](https://github.com/ras44/blog/edit/master/content/post/2019-01-05-why-i-use-a-fixed-version-of-r.Rmd)

Note: As with most of my articles, discussion is linux- and cloud-oriented.

## Why do I use a fixed version of R?

I will keep the motivation for [good versioning](https://semver.org/) and [reproducibility](http://adv-r.had.co.nz/Reproducibility.html) as short as possible:  R projects evolve over time, as do the packages that they rely on.  If you choose not to control package versions used in your R project, your code will eventually break and/or not be [reproducible](https://en.wikipedia.org/wiki/Replication_crisis)[^1].  These issues can also arise if you share your project with another user who has different versions of the required libraries installed at the system- or user-level.

## Packrat manages package

I use [Packrat](https://rstudio.github.io/packrat/) to control package vesions.  It is already integrated with RStudio.  Packrat ensures that all installed packages are stored *with* the project[^2].  Packrat also ensures that these packages are loaded when a project is opened.  With Packrat, I know that project A will always use ggplot2 2.5.0 and project B will always use ggplot2 2.5.0.  This is important if I want to be able to reproduce results in the future.

## Packrat package paths

Packrat stores compiled packages in `packrat/lib/<LINUX_FLAVOR>/<R_VERSION>`, an R-version-specific path, relative to the project's base directory.  An issue arises if I am using R version 3.5.0 one week and then system upgrades to R version 3.5.1 the next week: a Packrat project will not find the 3.5.0 libraries anymore, and I will need to rebuild all the packages I need to install them in the 3.5.1 path.

The easiest solution is to bind a fixed R version to the instance[^5]:

* [rstudio-instance](https://github.com/ras44/rstudio-instance) contains branches with scripts to set up a linux instance with fixed R and RStudio versions.  I `git clone` the repo and `git checkout` the branch suitable for the linux flavor, R-version, and RStudio version I want.  The scripts also ensure R is not auto-updated in the future.
* Once my fixed-R instance is set up, [rstudio-project](https://github.com/ras44/rstudio-project) contains an R-version specific base project with pre-built, Packrat-managed, fixed-versions of many popular data-science packages[^3].
* I `git clone` [rstudio-project](https://github.com/ras44/rstudio-project) to a new project directory locally and remove the existing `.git` directory so that I can turn it into a new git repo with `git init`.
* I open the project in RStudio and begin work.  All packages are pre-built, so I don't have to go through lengthy installs.  I can upgrade packages in the `Packrat Library` of the "Packages" tab, and then run `packrat::snapshot()` to save the any libraries and ugrades into my project's `packrat/` directory.
* If I ever need to duplicate results, I know can always build the same fixed-R instance, clone the project I created, and know that it will work exactly the same as when I previously worked on it... sometimes years earlier.

## Why I use a fixed version of R
* I want to ensure reproducibility and make sharing easier.
* I don't want to use docker containers[^4].
* I do not want or need to upgrade to the "latest" version of R: everything I'm doing works fine with the current versions and I want it to stay that way.
* Packrat ensures my project always uses the package versions stored with the project.
* Packrat stores packages in R-version-dependent paths.
* Using a fixed version of R ensures projects and packages remain tied to the R version.




[^1]: Unless you somehow exclusively use packages that are never updated, never implement version-breaking/major version updates, or always provide backwards-compatible version upgrades.  Many R packages are in major version 0, meaning there is no guarantee that a future release will maintain the same API.
[^2]: In the  `packrat/` directory
[^3]: rstudio-project contains all packages in the anaconda distribution and more
[^4]: docker containers may be a good alternate solution, but in this case we are not using them
[^5]: It [is possible](https://support.rstudio.com/hc/en-us/articles/215488098-Installing-multiple-versions-of-R-on-Linux) to have multiple R versions installed on a system, however I've avoided that for simplicity